export type BRVMOffer = {
  id: string
  title: string
  description: string
  type: string
  roi_percentage: number
  price_per_share: number
  minimum_investment: number
  is_active: boolean
}

export const BRVM_OFFERS: BRVMOffer[] = [
  {
    id: 'sdsc',
    title: 'Africa Global Logistics CI (SDSC)',
    description: 'Logistique et transport maritime - Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 6.2,
    price_per_share: 2210,
    minimum_investment: 2210,
    is_active: true,
  },
  {
    id: 'boab',
    title: 'Bank of Africa Bénin (BOAB)',
    description: 'Secteur Bancaire - Bénin.',
    type: 'Action',
    roi_percentage: 8.4,
    price_per_share: 8750,
    minimum_investment: 8750,
    is_active: true,
  },
  {
    id: 'boabf',
    title: 'Bank of Africa Burkina Faso (BOABF)',
    description: 'Secteur Bancaire - Burkina Faso.',
    type: 'Action',
    roi_percentage: 9.2,
    price_per_share: 6050,
    minimum_investment: 6050,
    is_active: true,
  },
  {
    id: 'boac',
    title: 'Bank of Africa Côte d’Ivoire (BOAC)',
    description: 'Secteur Bancaire - Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 7.8,
    price_per_share: 9500,
    minimum_investment: 9500,
    is_active: true,
  },
  {
    id: 'boam',
    title: 'Bank of Africa Mali (BOAM)',
    description: 'Secteur Bancaire - Mali.',
    type: 'Action',
    roi_percentage: 8.8,
    price_per_share: 5450,
    minimum_investment: 5450,
    is_active: true,
  },
  {
    id: 'boan',
    title: 'Bank of Africa Niger (BOAN)',
    description: 'Secteur Bancaire - Niger.',
    type: 'Action',
    roi_percentage: 9.5,
    price_per_share: 4790,
    minimum_investment: 4790,
    is_active: true,
  },
  {
    id: 'boas',
    title: 'Bank of Africa Sénégal (BOAS)',
    description: 'Secteur Bancaire - Sénégal.',
    type: 'Action',
    roi_percentage: 7.9,
    price_per_share: 7300,
    minimum_investment: 7300,
    is_active: true,
  },
  {
    id: 'bicb',
    title: 'Banque Internationale pour le Commerce du Bénin (BICB)',
    description: 'Secteur Bancaire et financier - Bénin.',
    type: 'Action',
    roi_percentage: 6.8,
    price_per_share: 6350,
    minimum_investment: 6350,
    is_active: true,
  },
  {
    id: 'bnbc',
    title: 'Bernabé Côte d’Ivoire (BNBC)',
    description: 'Distribution de quincaillerie et matériels industriels.',
    type: 'Action',
    roi_percentage: 4.5,
    price_per_share: 1755,
    minimum_investment: 1755,
    is_active: true,
  },
  {
    id: 'bicc',
    title: 'BICI Côte d’Ivoire (BICC)',
    description: 'Banque Ivoirienne pour le Commerce et l’Industrie.',
    type: 'Action',
    roi_percentage: 8.1,
    price_per_share: 28800,
    minimum_investment: 28800,
    is_active: true,
  },
  {
    id: 'cbibf',
    title: 'Coris Bank International Burkina Faso (CBIBF)',
    description: 'Banque commerciale et d’investissement.',
    type: 'Action',
    roi_percentage: 9.0,
    price_per_share: 29610,
    minimum_investment: 29610,
    is_active: true,
  },
  {
    id: 'cfac',
    title: 'CFAO Motors Côte d’Ivoire (CFAC)',
    description: 'Distribution automobile et équipements.',
    type: 'Action',
    roi_percentage: 5.6,
    price_per_share: 1575,
    minimum_investment: 1575,
    is_active: true,
  },
  {
    id: 'ciec',
    title: 'CIE (CIEC)',
    description: 'Compagnie Ivoirienne d’Électricité.',
    type: 'Action',
    roi_percentage: 8.8,
    price_per_share: 3980,
    minimum_investment: 3980,
    is_active: true,
  },
  {
    id: 'ecoc',
    title: 'Ecobank Côte d’Ivoire (ECOC)',
    description: 'Services bancaires et financiers.',
    type: 'Action',
    roi_percentage: 7.9,
    price_per_share: 7000,
    minimum_investment: 7000,
    is_active: true,
  },
  {
    id: 'etit',
    title: 'Ecobank Transnational Inc. (ETIT)',
    description: 'Holding bancaire panafricain.',
    type: 'Action',
    roi_percentage: 5.5,
    price_per_share: 64,
    minimum_investment: 3000,
    is_active: true,
  },
  {
    id: 'ftsc',
    title: 'Filtisac (FTSC)',
    description: 'Leader de l’emballage en Afrique de l’Ouest.',
    type: 'Action',
    roi_percentage: 6.1,
    price_per_share: 3200,
    minimum_investment: 3200,
    is_active: true,
  },
  {
    id: 'neic',
    title: 'NEI-CEDA (NEIC)',
    description: 'Nouvelles Éditions Ivoiriennes - CEDA.',
    type: 'Action',
    roi_percentage: 4.8,
    price_per_share: 2000,
    minimum_investment: 2000,
    is_active: true,
  },
  {
    id: 'nsbc',
    title: 'NSIA Banque Côte d’Ivoire (NSBC)',
    description: 'Groupe bancaire et assurances.',
    type: 'Action',
    roi_percentage: 8.1,
    price_per_share: 8500,
    minimum_investment: 8500,
    is_active: true,
  },
  {
    id: 'ontbf',
    title: 'Onatel Burkina Faso (ONTBF)',
    description: 'Opérateur télécom majeur au Burkina Faso.',
    type: 'Action',
    roi_percentage: 11.5,
    price_per_share: 2450,
    minimum_investment: 2450,
    is_active: true,
  },
  {
    id: 'orac',
    title: 'Orange Côte d’Ivoire (ORAC)',
    description: 'Opérateur télécoms et services numériques.',
    type: 'Action',
    roi_percentage: 7.2,
    price_per_share: 11500,
    minimum_investment: 11500,
    is_active: true,
  },
  {
    id: 'orgt',
    title: 'Oragroup (ORGT)',
    description: 'Groupe bancaire régional Orabank.',
    type: 'Action',
    roi_percentage: 6.5,
    price_per_share: 9000,
    minimum_investment: 9000,
    is_active: true,
  },
  {
    id: 'palc',
    title: 'PALMCI (PALC)',
    description: 'Production et transformation d’huile de palme.',
    type: 'Action',
    roi_percentage: 12.0,
    price_per_share: 10000,
    minimum_investment: 10000,
    is_active: true,
  },
  {
    id: 'prsc',
    title: 'Tractafric Motors CI (PRSC)',
    description: 'Vente et maintenance de véhicules industriels.',
    type: 'Action',
    roi_percentage: 5.6,
    price_per_share: 2350,
    minimum_investment: 2350,
    is_active: true,
  },
  {
    id: 'safc',
    title: 'SAFCA (SAFC)',
    description: 'Société Africaine de Crédit Automobile.',
    type: 'Action',
    roi_percentage: 6.3,
    price_per_share: 4200,
    minimum_investment: 4200,
    is_active: true,
  },
  {
    id: 'sdcc',
    title: 'SODECI (SDCC)',
    description: 'Société de Distribution d’Eau de Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 7.7,
    price_per_share: 8400,
    minimum_investment: 8400,
    is_active: true,
  },
  {
    id: 'semc',
    title: 'Crown Siem Côte d’Ivoire (SEMC)',
    description: 'Emballage métallique et sous-traitance industrielle.',
    type: 'Action',
    roi_percentage: 4.9,
    price_per_share: 1500,
    minimum_investment: 1500,
    is_active: true,
  },
  {
    id: 'sgbc',
    title: 'SGBCI (SGBC)',
    description: 'Société Générale Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 9.1,
    price_per_share: 16500,
    minimum_investment: 16500,
    is_active: true,
  },
  {
    id: 'shec',
    title: 'Vivo Energy Côte d’Ivoire (SHEC)',
    description: 'Distribution et commercialisation de carburants.',
    type: 'Action',
    roi_percentage: 6.4,
    price_per_share: 1210,
    minimum_investment: 1210,
    is_active: true,
  },
  {
    id: 'sibc',
    title: 'Société Ivoirienne de Banque (SIBC)',
    description: 'Filiale du groupe Attijariwafa bank.',
    type: 'Action',
    roi_percentage: 7.5,
    price_per_share: 9900,
    minimum_investment: 9900,
    is_active: true,
  },
  {
    id: 'sicc',
    title: 'SICOR Côte d’Ivoire (SICC)',
    description: 'Société Ivoirienne de Coco Râpé.',
    type: 'Action',
    roi_percentage: 4.8,
    price_per_share: 7000,
    minimum_investment: 7000,
    is_active: true,
  },
  {
    id: 'sphc',
    title: 'SAPH Côte d’Ivoire (SPHC)',
    description: 'Société Africaine de Plantations d’Hévéas.',
    type: 'Action',
    roi_percentage: 6.8,
    price_per_share: 7550,
    minimum_investment: 7550,
    is_active: true,
  },
  {
    id: 'slbc',
    title: 'SOLIBRA (SLBC)',
    description: 'Société de Limonaderies et Brasseries d’Afrique.',
    type: 'Action',
    roi_percentage: 4.5,
    price_per_share: 5500,
    minimum_investment: 5500,
    is_active: true,
  },
  {
    id: 'smbc',
    title: 'SMB (SMBC)',
    description: 'Société Multinationale de Bitumes.',
    type: 'Action',
    roi_percentage: 7.4,
    price_per_share: 7000,
    minimum_investment: 7000,
    is_active: true,
  },
  {
    id: 'snts',
    title: 'Sonatel (SNTS)',
    description: 'Télécommunications et réseaux en Afrique de l’Ouest.',
    type: 'Action',
    roi_percentage: 8.5,
    price_per_share: 16000,
    minimum_investment: 16000,
    is_active: true,
  },
  {
    id: 'sogc',
    title: 'SOGB (SOGC)',
    description: 'Société Grand-Bereby d’Hévéas et de Palmier à Huile.',
    type: 'Action',
    roi_percentage: 8.2,
    price_per_share: 7000,
    minimum_investment: 7000,
    is_active: true,
  },
  {
    id: 'stac',
    title: 'SETAO (STAC)',
    description: 'Société d’Études et de Travaux pour l’Afrique de l’Ouest.',
    type: 'Action',
    roi_percentage: 5.9,
    price_per_share: 4000,
    minimum_investment: 4000,
    is_active: true,
  },
  {
    id: 'stbc',
    title: 'SITAB Côte d’Ivoire (STBC)',
    description: 'Société Ivoirienne des Tabacs.',
    type: 'Action',
    roi_percentage: 6.7,
    price_per_share: 3100,
    minimum_investment: 3100,
    is_active: true,
  },
  {
    id: 'unlc',
    title: 'Unilever Côte d’Ivoire (UNLC)',
    description: 'Fabrication et vente de produits de grande consommation.',
    type: 'Action',
    roi_percentage: 5.1,
    price_per_share: 50500,
    minimum_investment: 50500,
    is_active: true,
  },
  {
    id: 'unxc',
    title: 'Uniwax (UNXC)',
    description: 'Fabrication et distribution de tissus wax.',
    type: 'Action',
    roi_percentage: 5.3,
    price_per_share: 1340,
    minimum_investment: 1340,
    is_active: true,
  },
  {
    id: 'ttlc',
    title: 'TotalEnergies Marketing Côte d’Ivoire (TTLC)',
    description: 'Réseau de stations-services et lubrifiants CI.',
    type: 'Action',
    roi_percentage: 6.2,
    price_per_share: 2800,
    minimum_investment: 2800,
    is_active: true,
  },
  {
    id: 'ttls',
    title: 'TotalEnergies Marketing Sénégal (TTLS)',
    description: 'Réseau de distribution pétrolière Sénégal.',
    type: 'Action',
    roi_percentage: 6.8,
    price_per_share: 1550,
    minimum_investment: 1550,
    is_active: true,
  },
  {
    id: 'sivc',
    title: 'Air Liquide Côte d’Ivoire (Erium CI) (SIVC)',
    description: 'Production et distribution de gaz industriels et médicaux.',
    type: 'Action',
    roi_percentage: 5.7,
    price_per_share: 315000,
    minimum_investment: 315000,
    is_active: true,
  },
  {
    id: 'abjc',
    title: 'Servair Abidjan (ABJC)',
    description: 'Restauration et services aéroportuaires.',
    type: 'Action',
    roi_percentage: 9.8,
    price_per_share: 3150,
    minimum_investment: 3150,
    is_active: true,
  },
  {
    id: 'ntlc',
    title: 'Nestlé Côte d’Ivoire (NTLC)',
    description: 'Transformation et distribution de produits alimentaires.',
    type: 'Action',
    roi_percentage: 5.8,
    price_per_share: 8500,
    minimum_investment: 8500,
    is_active: true,
  },
  {
    id: 'scrc',
    title: 'Sucrivoire (SCRC)',
    description: 'Exploitation et raffinage de canne à sucre.',
    type: 'Action',
    roi_percentage: 3.5,
    price_per_share: 15000,
    minimum_investment: 15000,
    is_active: true,
  },
  {
    id: 'cabc',
    title: 'Sicable Côte d’Ivoire (CABC)',
    description: 'Fabrication de câbles électriques et téléphoniques.',
    type: 'Action',
    roi_percentage: 4.8,
    price_per_share: 7000,
    minimum_investment: 7000,
    is_active: true,
  },
  {
    id: 'sdcc-eau',
    title: 'Société de Distribution d’Eau de Côte d’Ivoire (SDCC)',
    description: 'Distribution et traitement de l’eau potable en Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 7.7,
    price_per_share: 8400,
    minimum_investment: 8400,
    is_active: true,
  },
  {
    id: 'bbgc',
    title: 'Bridge Bank Group Côte d’Ivoire (BBGC)',
    description: 'Banque d’affaires et services aux entreprises.',
    type: 'Action',
    roi_percentage: 8.3,
    price_per_share: 6750,
    minimum_investment: 6750,
    is_active: true,
  },
]
