export type BRVMOffer = {
  id: string
  symbol: string
  title: string
  description: string
  type: string
  roi_percentage: number
  price_per_share: number
  minimum_investment: number
  is_active: boolean
}

export const BRVM_OFFERS: BRVMOffer[] = [
  {
    id: 'abjc',
    symbol: 'ABJC',
    title: 'Servair Abidjan (ABJC)',
    description: 'Restauration et services aéroportuaires.',
    type: 'Action',
    roi_percentage: 9.8,
    price_per_share: 2990,
    minimum_investment: 2990,
    is_active: true,
  },
  {
    id: 'bicb',
    symbol: 'BICB',
    title: 'BIIC Bénin (BICB)',
    description: 'Secteur Bancaire et financier - Bénin.',
    type: 'Action',
    roi_percentage: 6.8,
    price_per_share: 6495,
    minimum_investment: 6495,
    is_active: true,
  },
  {
    id: 'bicc',
    symbol: 'BICC',
    title: 'BICI Côte d’Ivoire (BICC)',
    description: 'Banque Ivoirienne pour le Commerce et l’Industrie.',
    type: 'Action',
    roi_percentage: 8.1,
    price_per_share: 28100,
    minimum_investment: 28100,
    is_active: true,
  },
  {
    id: 'bnbc',
    symbol: 'BNBC',
    title: 'Bernabé Côte d’Ivoire (BNBC)',
    description: 'Distribution de quincaillerie et matériels industriels.',
    type: 'Action',
    roi_percentage: 4.5,
    price_per_share: 2000,
    minimum_investment: 2000,
    is_active: true,
  },
  {
    id: 'boab',
    symbol: 'BOAB',
    title: 'Bank of Africa Bénin (BOAB)',
    description: 'Secteur Bancaire - Bénin.',
    type: 'Action',
    roi_percentage: 8.4,
    price_per_share: 8700,
    minimum_investment: 8700,
    is_active: true,
  },
  {
    id: 'boabf',
    symbol: 'BOABF',
    title: 'Bank of Africa Burkina Faso (BOABF)',
    description: 'Secteur Bancaire - Burkina Faso.',
    type: 'Action',
    roi_percentage: 9.2,
    price_per_share: 7000,
    minimum_investment: 7000,
    is_active: true,
  },
  {
    id: 'boac',
    symbol: 'BOAC',
    title: 'Bank of Africa Côte d’Ivoire (BOAC)',
    description: 'Secteur Bancaire - Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 7.8,
    price_per_share: 9745,
    minimum_investment: 9745,
    is_active: true,
  },
  {
    id: 'boam',
    symbol: 'BOAM',
    title: 'Bank of Africa Mali (BOAM)',
    description: 'Secteur Bancaire - Mali.',
    type: 'Action',
    roi_percentage: 8.8,
    price_per_share: 5755,
    minimum_investment: 5755,
    is_active: true,
  },
  {
    id: 'boan',
    symbol: 'BOAN',
    title: 'Bank of Africa Niger (BOAN)',
    description: 'Secteur Bancaire - Niger.',
    type: 'Action',
    roi_percentage: 9.5,
    price_per_share: 5350,
    minimum_investment: 5350,
    is_active: true,
  },
  {
    id: 'boas',
    symbol: 'BOAS',
    title: 'Bank of Africa Sénégal (BOAS)',
    description: 'Secteur Bancaire - Sénégal.',
    type: 'Action',
    roi_percentage: 7.9,
    price_per_share: 7500,
    minimum_investment: 7500,
    is_active: true,
  },
  {
    id: 'cabc',
    symbol: 'CABC',
    title: 'Crown Siem CI (CABC)',
    description: 'Emballage métallique et sous-traitance industrielle.',
    type: 'Action',
    roi_percentage: 4.9,
    price_per_share: 3650,
    minimum_investment: 3650,
    is_active: true,
  },
  {
    id: 'cbibf',
    symbol: 'CBIBF',
    title: 'Coris Bank International (CBIBF)',
    description: 'Banque commerciale et d’investissement.',
    type: 'Action',
    roi_percentage: 9.0,
    price_per_share: 27500,
    minimum_investment: 27500,
    is_active: true,
  },
  {
    id: 'cfac',
    symbol: 'CFAC',
    title: 'CFAO Motors CI (CFAC)',
    description: 'Distribution automobile et équipements.',
    type: 'Action',
    roi_percentage: 5.6,
    price_per_share: 1710,
    minimum_investment: 1710,
    is_active: true,
  },
  {
    id: 'ciec',
    symbol: 'CIEC',
    title: 'Compagnie Ivoirienne d’Électricité (CIEC)',
    description: 'Compagnie Ivoirienne d’Électricité.',
    type: 'Action',
    roi_percentage: 8.8,
    price_per_share: 5105,
    minimum_investment: 5105,
    is_active: true,
  },
  {
    id: 'ecoc',
    symbol: 'ECOC',
    title: 'Ecobank Côte d’Ivoire (ECOC)',
    description: 'Services bancaires et financiers.',
    type: 'Action',
    roi_percentage: 7.9,
    price_per_share: 15700,
    minimum_investment: 15700,
    is_active: true,
  },
  {
    id: 'etit',
    symbol: 'ETIT',
    title: 'Ecobank Transnational (ETIT)',
    description: 'Holding bancaire panafricain.',
    type: 'Action',
    roi_percentage: 5.5,
    price_per_share: 63,
    minimum_investment: 3000,
    is_active: true,
  },
  {
    id: 'ftsc',
    symbol: 'FTSC',
    title: 'Filtisac (FTSC)',
    description: 'Leader de l’emballage en Afrique de l’Ouest.',
    type: 'Action',
    roi_percentage: 6.1,
    price_per_share: 1990,
    minimum_investment: 1990,
    is_active: true,
  },
  {
    id: 'lnbb',
    symbol: 'LNBB',
    title: 'Loterie Nationale du Bénin (LNBB)',
    description: 'Loterie Nationale du Bénin.',
    type: 'Action',
    roi_percentage: 7.2,
    price_per_share: 4250,
    minimum_investment: 4250,
    is_active: true,
  },
  {
    id: 'neic',
    symbol: 'NEIC',
    title: 'NEI-CEDA (NEIC)',
    description: 'Nouvelles Éditions Ivoiriennes - CEDA.',
    type: 'Action',
    roi_percentage: 4.8,
    price_per_share: 2150,
    minimum_investment: 2150,
    is_active: true,
  },
  {
    id: 'nsbc',
    symbol: 'NSBC',
    title: 'NSIA Banque CI (NSBC)',
    description: 'Groupe bancaire et assurances.',
    type: 'Action',
    roi_percentage: 8.1,
    price_per_share: 22000,
    minimum_investment: 22000,
    is_active: true,
  },
  {
    id: 'ntlc',
    symbol: 'NTLC',
    title: 'Nestlé Côte d’Ivoire (NTLC)',
    description: 'Transformation et distribution de produits alimentaires.',
    type: 'Action',
    roi_percentage: 5.8,
    price_per_share: 15930,
    minimum_investment: 15930,
    is_active: true,
  },
  {
    id: 'ontbf',
    symbol: 'ONTBF',
    title: 'Onatel Burkina Faso (ONTBF)',
    description: 'Opérateur télécom majeur au Burkina Faso.',
    type: 'Action',
    roi_percentage: 11.5,
    price_per_share: 2700,
    minimum_investment: 2700,
    is_active: true,
  },
  {
    id: 'orac',
    symbol: 'ORAC',
    title: 'Orange Côte d’Ivoire (ORAC)',
    description: 'Opérateur télécoms et services numériques.',
    type: 'Action',
    roi_percentage: 7.2,
    price_per_share: 16165,
    minimum_investment: 16165,
    is_active: true,
  },
  {
    id: 'orgt',
    symbol: 'ORGT',
    title: 'Oragroup (ORGT)',
    description: 'Groupe bancaire régional Orabank.',
    type: 'Action',
    roi_percentage: 6.5,
    price_per_share: 2670,
    minimum_investment: 2670,
    is_active: true,
  },
  {
    id: 'palc',
    symbol: 'PALC',
    title: 'Palm CI (PALC)',
    description: 'Production et transformation d’huile de palme.',
    type: 'Action',
    roi_percentage: 12.0,
    price_per_share: 8700,
    minimum_investment: 8700,
    is_active: true,
  },
  {
    id: 'prsc',
    symbol:'PRSSC'
    title: 'Tractafric Motors CI (PRSC)',
    description: 'Vente et maintenance de véhicules industriels.',
    type: 'Action',
    roi_percentage: 5.6,
    price_per_share: 4295,
    minimum_investment: 4295,
    is_active: true,
  },
  {
    id: 'safc',
    symbol:'SAFC'
    title: 'Alios Finance (SAFC)',
    description: 'Société Africaine de Crédit Automobile.',
    type: 'Action',
    roi_percentage: 6.3,
    price_per_share: 4550,
    minimum_investment: 4550,
    is_active: true,
  },
  {
    id: 'scrc',
    symbol: 'SCRC',
    title: 'Sucrivoire (SCRC)',
    description: 'Exploitation et raffinage de canne à sucre.',
    type: 'Action',
    roi_percentage: 3.5,
    price_per_share: 3530,
    minimum_investment: 3530,
    is_active: true,
  },
  {
    id: 'sdcc',
    symbol:'SDCC'
    title: 'SODECI (SDCC)',
    description: 'Société de Distribution d’Eau de Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 7.7,
    price_per_share: 11300,
    minimum_investment: 11300,
    is_active: true,
  },
  {
    id: 'sdsc',
    symbol:'SDSC'
    title: 'Africa Global Logistics CI (SDSC)',
    description: 'Logistique et transport maritime - Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 6.2,
    price_per_share: 2525,
    minimum_investment: 2525,
    is_active: true,
  },
  {
    id: 'semc',
    symbol:'SEMC'
    title: 'Siem Côte d’Ivoire (SEMC)',
    description: 'Emballage métallique et sous-traitance industrielle.',
    type: 'Action',
    roi_percentage: 4.9,
    price_per_share: 1535,
    minimum_investment: 1535,
    is_active: true,
  },
  {
    id: 'sgbc',
    symbol:'SGBC'
    title: 'Société Générale CI (SGBC)',
    description: 'Société Générale Côte d’Ivoire.',
    type: 'Action',
    roi_percentage: 9.1,
    price_per_share: 38200,
    minimum_investment: 38200,
    is_active: true,
  },
  {
    id: 'shec',
    symbol:'SHEC'
    title: 'Sicable (SHEC)',
    description: 'Fabrication de câbles électriques et téléphoniques.',
    type: 'Action',
    roi_percentage: 6.4,
    price_per_share: 2200,
    minimum_investment: 2200,
    is_active: true,
  },
  {
    id: 'sibc',
    symbol:'SIBC'
    title: 'Société Ivoirienne de Banque (SIBC)',
    description: 'Filiale du groupe Attijariwafa bank.',
    type: 'Action',
    roi_percentage: 7.5,
    price_per_share: 8900,
    minimum_investment: 8900,
    is_active: true,
  },
  {
    id: 'sicc',
    symbol:'SICC'
    title: 'SICOR (SICC)',
    description: 'Société Ivoirienne de Coco Râpé.',
    type: 'Action',
    roi_percentage: 4.8,
    price_per_share: 5100,
    minimum_investment: 5100,
    is_active: true,
  },
  {
    id: 'sivc',
    symbol:'SIVC'
    title: 'Air Liquide CI (SIVC)',
    description: 'Production et distribution de gaz industriels et médicaux.',
    type: 'Action',
    roi_percentage: 5.7,
    price_per_share: 2530,
    minimum_investment: 2530,
    is_active: true,
  },
  {
    id: 'slbc',
    symbol:'SLBC'
    title: 'SOLIBRA (SLBC)',
    description: 'Société de Limonaderies et Brasseries d’Afrique.',
    type: 'Action',
    roi_percentage: 4.5,
    price_per_share: 39900,
    minimum_investment: 39900,
    is_active: true,
  },
  {
    id: 'smbc',
    symbol:'SMBC'
    title: 'SMB CI (SMBC)',
    description: 'Société Multinationale de Bitumes.',
    type: 'Action',
    roi_percentage: 7.4,
    price_per_share: 16400,
    minimum_investment: 16400,
    is_active: true,
  },
  {
    id: 'snts',
    symbol:'SNTS'
    title: 'Sonatel (SNTS)',
    description: 'Télécommunications et réseaux en Afrique de l’Ouest.',
    type: 'Action',
    roi_percentage: 8.5,
    price_per_share: 32450,
    minimum_investment: 32450,
    is_active: true,
  },
  {
    id: 'sogc',
    symbol:'SOGC'
    title: 'SOGB (SOGC)',
    description: 'Société Grand-Bereby d’Hévéas et de Palmier à Huile.',
    type: 'Action',
    roi_percentage: 8.2,
    price_per_share: 8005,
    minimum_investment: 8005,
    is_active: true,
  },
  {
    id: 'sphc',
    symbol:'SPHC'
    title: 'SAPH (SPHC)',
    description: 'Société Africaine de Plantations d’Hévéas.',
    type: 'Action',
    roi_percentage: 6.8,
    price_per_share: 7500,
    minimum_investment: 7500,
    is_active: true,
  },
  {
    id: 'stac',
    symbol:'STAC'
    title: 'SITAB (STAC)',
    description: 'Société Ivoirienne des Tabacs.',
    type: 'Action',
    roi_percentage: 5.9,
    price_per_share: 3185,
    minimum_investment: 3185,
    is_active: true,
  },
  {
    id: 'stbc',
    symbol:'STBC'
    title: 'SETAO (STBC)',
    description: 'Société d’Études et de Travaux pour l’Afrique de l’Ouest.',
    type: 'Action',
    roi_percentage: 6.7,
    price_per_share: 24195,
    minimum_investment: 24195,
    is_active: true,
  },
  {
    id: 'ttlc',
    symbol:'TTLC'
    title: 'TOTALENERGIES CI (TTLC)',
    description: 'Réseau de stations-services et lubrifiants CI.',
    type: 'Action',
    roi_percentage: 6.2,
    price_per_share: 2900,
    minimum_investment: 2900,
    is_active: true,
  },
  {
    id: 'ttls',
    symbol:'TTLS'
    title: 'TOTALENERGIES SÉNÉGAL (TTLS)',
    description: 'Réseau de distribution pétrolière Sénégal.',
    type: 'Action',
    roi_percentage: 6.8,
    price_per_share: 4110,
    minimum_investment: 4110,
    is_active: true,
  },
  {
    id: 'unlc',
    symbol:'UNLC'
    title: 'UNILEVER CI (UNLC)',
    description: 'Fabrication et vente de produits de grande consommation.',
    type: 'Action',
    roi_percentage: 5.1,
    price_per_share: 53735,
    minimum_investment: 53735,
    is_active: true,
  },
  {
    id: 'unxc',
    symbol:'UNXC'
    title: 'UNIWAX (UNXC)',
    description: 'Fabrication et distribution de tissus wax.',
    type: 'Action',
    roi_percentage: 5.3,
    price_per_share: 1660,
    minimum_investment: 1660,
    is_active: true,
  },
  {
    id: 'vivo',
    symbol:'VIVO'
    title: 'VIVO ENERGY CI (VIVO)',
    description: 'Distribution et commercialisation de carburants.',
    type: 'Action',
    roi_percentage: 6.4,
    price_per_share: 1800,
    minimum_investment: 1800,
    is_active: true,
  },
]
