-- Mettre à jour les 48 prix BRVM (à exécuter dans Supabase SQL Editor)
UPDATE public.investment_offers SET price_per_share = 2210, minimum_investment = 2210 WHERE title ILIKE '%SDSC%';
UPDATE public.investment_offers SET price_per_share = 8750, minimum_investment = 8750 WHERE title ILIKE '%BOAB%' AND title NOT ILIKE '%BOABF%';
UPDATE public.investment_offers SET price_per_share = 6050, minimum_investment = 6050 WHERE title ILIKE '%BOABF%';
UPDATE public.investment_offers SET price_per_share = 9500, minimum_investment = 9500 WHERE title ILIKE '%BOAC%';
UPDATE public.investment_offers SET price_per_share = 5450, minimum_investment = 5450 WHERE title ILIKE '%BOAM%';
UPDATE public.investment_offers SET price_per_share = 4790, minimum_investment = 4790 WHERE title ILIKE '%BOAN%';
UPDATE public.investment_offers SET price_per_share = 7300, minimum_investment = 7300 WHERE title ILIKE '%BOAS%';
UPDATE public.investment_offers SET price_per_share = 6350, minimum_investment = 6350 WHERE title ILIKE '%BICB%';
UPDATE public.investment_offers SET price_per_share = 1755, minimum_investment = 1755 WHERE title ILIKE '%BNBC%';
UPDATE public.investment_offers SET price_per_share = 28800, minimum_investment = 28800 WHERE title ILIKE '%BICC%' OR title ILIKE '%BICI%';
UPDATE public.investment_offers SET price_per_share = 29610, minimum_investment = 29610 WHERE title ILIKE '%CBIBF%';
UPDATE public.investment_offers SET price_per_share = 1575, minimum_investment = 1575 WHERE title ILIKE '%CFAC%';
UPDATE public.investment_offers SET price_per_share = 3980, minimum_investment = 3980 WHERE title ILIKE '%CIEC%';
UPDATE public.investment_offers SET price_per_share = 7000, minimum_investment = 7000 WHERE title ILIKE '%ECOC%' AND title NOT ILIKE '%ETIT%';
UPDATE public.investment_offers SET price_per_share = 64, minimum_investment = 3000 WHERE title ILIKE '%ETIT%';
UPDATE public.investment_offers SET price_per_share = 3200, minimum_investment = 3200 WHERE title ILIKE '%FTSC%';
UPDATE public.investment_offers SET price_per_share = 2000, minimum_investment = 2000 WHERE title ILIKE '%NEIC%';
UPDATE public.investment_offers SET price_per_share = 8500, minimum_investment = 8500 WHERE title ILIKE '%NSBC%';
UPDATE public.investment_offers SET price_per_share = 2450, minimum_investment = 2450 WHERE title ILIKE '%ONTBF%';
UPDATE public.investment_offers SET price_per_share = 11500, minimum_investment = 11500 WHERE title ILIKE '%ORAC%';
UPDATE public.investment_offers SET price_per_share = 9000, minimum_investment = 9000 WHERE title ILIKE '%ORGT%';
UPDATE public.investment_offers SET price_per_share = 10000, minimum_investment = 10000 WHERE title ILIKE '%PALC%';
UPDATE public.investment_offers SET price_per_share = 2350, minimum_investment = 2350 WHERE title ILIKE '%PRSC%';
UPDATE public.investment_offers SET price_per_share = 4200, minimum_investment = 4200 WHERE title ILIKE '%SAFC%';
UPDATE public.investment_offers SET price_per_share = 8400, minimum_investment = 8400 WHERE title ILIKE '%SDCC%';
UPDATE public.investment_offers SET price_per_share = 1500, minimum_investment = 1500 WHERE title ILIKE '%SEMC%';
UPDATE public.investment_offers SET price_per_share = 16500, minimum_investment = 16500 WHERE title ILIKE '%SGBC%';
UPDATE public.investment_offers SET price_per_share = 1210, minimum_investment = 1210 WHERE title ILIKE '%SHEC%';
UPDATE public.investment_offers SET price_per_share = 9900, minimum_investment = 9900 WHERE title ILIKE '%SIBC%';
UPDATE public.investment_offers SET price_per_share = 7000, minimum_investment = 7000 WHERE title ILIKE '%SICC%';
UPDATE public.investment_offers SET price_per_share = 7550, minimum_investment = 7550 WHERE title ILIKE '%SPHC%';
UPDATE public.investment_offers SET price_per_share = 5500, minimum_investment = 5500 WHERE title ILIKE '%SLBC%';
UPDATE public.investment_offers SET price_per_share = 7000, minimum_investment = 7000 WHERE title ILIKE '%SMBC%';
UPDATE public.investment_offers SET price_per_share = 16000, minimum_investment = 16000 WHERE title ILIKE '%SNTS%';
UPDATE public.investment_offers SET price_per_share = 7000, minimum_investment = 7000 WHERE title ILIKE '%SOGC%';
UPDATE public.investment_offers SET price_per_share = 4000, minimum_investment = 4000 WHERE title ILIKE '%STAC%';
UPDATE public.investment_offers SET price_per_share = 3100, minimum_investment = 3100 WHERE title ILIKE '%STBC%';
UPDATE public.investment_offers SET price_per_share = 50500, minimum_investment = 50500 WHERE title ILIKE '%UNLC%';
UPDATE public.investment_offers SET price_per_share = 1340, minimum_investment = 1340 WHERE title ILIKE '%UNXC%';
UPDATE public.investment_offers SET price_per_share = 2800, minimum_investment = 2800 WHERE title ILIKE '%TTLC%';
UPDATE public.investment_offers SET price_per_share = 1550, minimum_investment = 1550 WHERE title ILIKE '%TTLS%';
UPDATE public.investment_offers SET price_per_share = 315000, minimum_investment = 315000 WHERE title ILIKE '%SIVC%';
UPDATE public.investment_offers SET price_per_share = 3150, minimum_investment = 3150 WHERE title ILIKE '%ABJC%';
UPDATE public.investment_offers SET price_per_share = 8500, minimum_investment = 8500 WHERE title ILIKE '%NTLC%';
UPDATE public.investment_offers SET price_per_share = 15000, minimum_investment = 15000 WHERE title ILIKE '%SCRC%';
UPDATE public.investment_offers SET price_per_share = 7000, minimum_investment = 7000 WHERE title ILIKE '%CABC%';
UPDATE public.investment_offers SET price_per_share = 6750, minimum_investment = 6750 WHERE title ILIKE '%Bridge Bank%';
