-- Mettre à jour les 48 prix BRVM (à exécuter dans Supabase SQL Editor)
UPDATE public.investment_offers SET price_per_share = 2900, minimum_investment = 2900 WHERE title ILIKE '%ABJC%';
UPDATE public.investment_offers SET price_per_share = 5455, minimum_investment = 5455 WHERE title ILIKE '%BICB%';
UPDATE public.investment_offers SET price_per_share = 28970, minimum_investment = 28970 WHERE title ILIKE '%BICC%' OR title ILIKE '%BICI%';
UPDATE public.investment_offers SET price_per_share = 1650, minimum_investment = 1650 WHERE title ILIKE '%BNBC%';
UPDATE public.investment_offers SET price_per_share = 8795, minimum_investment = 8795 WHERE title ILIKE '%BOAB%' AND title NOT ILIKE '%BOABF%';
UPDATE public.investment_offers SET price_per_share = 5580, minimum_investment = 5580 WHERE title ILIKE '%BOABF%';
UPDATE public.investment_offers SET price_per_share = 8000, minimum_investment = 8000 WHERE title ILIKE '%BOAC%';
UPDATE public.investment_offers SET price_per_share = 2800, minimum_investment = 2800 WHERE title ILIKE '%BOAM%';
UPDATE public.investment_offers SET price_per_share = 4500, minimum_investment = 4500 WHERE title ILIKE '%BOAN%';
UPDATE public.investment_offers SET price_per_share = 3500, minimum_investment = 3500 WHERE title ILIKE '%BOAS%';
UPDATE public.investment_offers SET price_per_share = 1200, minimum_investment = 1200 WHERE title ILIKE '%CABC%' OR title ILIKE '%Crown Siem%';
UPDATE public.investment_offers SET price_per_share = 11000, minimum_investment = 11000 WHERE title ILIKE '%CBIBF%';
UPDATE public.investment_offers SET price_per_share = 1765, minimum_investment = 1765 WHERE title ILIKE '%CFAC%';
UPDATE public.investment_offers SET price_per_share = 4755, minimum_investment = 4755 WHERE title ILIKE '%CIEC%';
UPDATE public.investment_offers SET price_per_share = 16400, minimum_investment = 16400 WHERE title ILIKE '%ECOC%' AND title NOT ILIKE '%ETIT%';
UPDATE public.investment_offers SET price_per_share = 20, minimum_investment = 3000 WHERE title ILIKE '%ETIT%';
UPDATE public.investment_offers SET price_per_share = 2400, minimum_investment = 2400 WHERE title ILIKE '%FTSC%';
UPDATE public.investment_offers SET price_per_share = 4005, minimum_investment = 4005 WHERE title ILIKE '%LNBB%';
UPDATE public.investment_offers SET price_per_share = 500, minimum_investment = 500 WHERE title ILIKE '%NEIC%';
UPDATE public.investment_offers SET price_per_share = 8500, minimum_investment = 8500 WHERE title ILIKE '%NSBC%';
UPDATE public.investment_offers SET price_per_share = 13200, minimum_investment = 13200 WHERE title ILIKE '%NTLC%' OR title ILIKE '%Nestlé Côte%';
UPDATE public.investment_offers SET price_per_share = 2905, minimum_investment = 2905 WHERE title ILIKE '%ONTBF%';
UPDATE public.investment_offers SET price_per_share = 16930, minimum_investment = 16930 WHERE title ILIKE '%ORAC%';
UPDATE public.investment_offers SET price_per_share = 2855, minimum_investment = 2855 WHERE title ILIKE '%ORGT%';
UPDATE public.investment_offers SET price_per_share = 8255, minimum_investment = 8255 WHERE title ILIKE '%PALC%';
UPDATE public.investment_offers SET price_per_share = 4410, minimum_investment = 4410 WHERE title ILIKE '%PRSC%';
UPDATE public.investment_offers SET price_per_share = 3800, minimum_investment = 3800 WHERE title ILIKE '%SAFC%' OR title ILIKE '%Alios%';
UPDATE public.investment_offers SET price_per_share = 2940, minimum_investment = 2940 WHERE title ILIKE '%SCRC%';
UPDATE public.investment_offers SET price_per_share = 7000, minimum_investment = 7000 WHERE title ILIKE '%SDCC%';
UPDATE public.investment_offers SET price_per_share = 1950, minimum_investment = 1950 WHERE title ILIKE '%SDSC%';
UPDATE public.investment_offers SET price_per_share = 7000, minimum_investment = 7000 WHERE title ILIKE '%SEMC%' OR title ILIKE '%Siem%';
UPDATE public.investment_offers SET price_per_share = 37505, minimum_investment = 37505 WHERE title ILIKE '%SGBC%';
UPDATE public.investment_offers SET price_per_share = 15000, minimum_investment = 15000 WHERE title ILIKE '%SHEC%' OR title ILIKE '%Sicable%';
UPDATE public.investment_offers SET price_per_share = 8900, minimum_investment = 8900 WHERE title ILIKE '%SIBC%';
UPDATE public.investment_offers SET price_per_share = 4135, minimum_investment = 4135 WHERE title ILIKE '%SICC%' OR title ILIKE '%SICOR%';
UPDATE public.investment_offers SET price_per_share = 40000, minimum_investment = 40000 WHERE title ILIKE '%SIVC%' OR title ILIKE '%Air Liquide%';
UPDATE public.investment_offers SET price_per_share = 150000, minimum_investment = 150000 WHERE title ILIKE '%SLBC%';
UPDATE public.investment_offers SET price_per_share = 13330, minimum_investment = 13330 WHERE title ILIKE '%SMBC%';
UPDATE public.investment_offers SET price_per_share = 28500, minimum_investment = 28500 WHERE title ILIKE '%SNTS%';
UPDATE public.investment_offers SET price_per_share = 8000, minimum_investment = 8000 WHERE title ILIKE '%SOGC%';
UPDATE public.investment_offers SET price_per_share = 7720, minimum_investment = 7720 WHERE title ILIKE '%SPHC%';
UPDATE public.investment_offers SET price_per_share = 1000, minimum_investment = 1000 WHERE title ILIKE '%STAC%' OR title ILIKE '%SITAB%';
UPDATE public.investment_offers SET price_per_share = 100000, minimum_investment = 100000 WHERE title ILIKE '%STBC%' OR title ILIKE '%SETAO%';
UPDATE public.investment_offers SET price_per_share = 2890, minimum_investment = 2890 WHERE title ILIKE '%TTLC%';
UPDATE public.investment_offers SET price_per_share = 3495, minimum_investment = 3495 WHERE title ILIKE '%TTLS%';
UPDATE public.investment_offers SET price_per_share = 58000, minimum_investment = 58000 WHERE title ILIKE '%UNLC%';
UPDATE public.investment_offers SET price_per_share = 900, minimum_investment = 900 WHERE title ILIKE '%UNXC%';
UPDATE public.investment_offers SET price_per_share = 1800, minimum_investment = 1800 WHERE title ILIKE '%VIVO%';
