-- Mettre à jour les prix existants sans supprimer les offres (à exécuter dans Supabase SQL Editor)
UPDATE public.investment_offers SET price_per_share = 3200, minimum_investment = 3200 WHERE title ILIKE '%ABJC%';
UPDATE public.investment_offers SET price_per_share = 6275, minimum_investment = 6275 WHERE title ILIKE '%BICB%';
UPDATE public.investment_offers SET price_per_share = 29250, minimum_investment = 29250 WHERE title ILIKE '%BICC%';
UPDATE public.investment_offers SET price_per_share = 1985, minimum_investment = 1985 WHERE title ILIKE '%BNBC%';
UPDATE public.investment_offers SET price_per_share = 9100, minimum_investment = 9100 WHERE title ILIKE '%BOAB%' AND title NOT ILIKE '%BOABF%';
UPDATE public.investment_offers SET price_per_share = 5940, minimum_investment = 5940 WHERE title ILIKE '%BOABF%';
UPDATE public.investment_offers SET price_per_share = 9100, minimum_investment = 9100 WHERE title ILIKE '%BOAC%';
UPDATE public.investment_offers SET price_per_share = 4965, minimum_investment = 4965 WHERE title ILIKE '%BOAM%';
UPDATE public.investment_offers SET price_per_share = 4200, minimum_investment = 4200 WHERE title ILIKE '%BOAN%';
UPDATE public.investment_offers SET price_per_share = 7305, minimum_investment = 7305 WHERE title ILIKE '%BOAS%';
UPDATE public.investment_offers SET price_per_share = 4500, minimum_investment = 4500 WHERE title ILIKE '%CABC%';
UPDATE public.investment_offers SET price_per_share = 24000, minimum_investment = 24000 WHERE title ILIKE '%CBIBF%';
UPDATE public.investment_offers SET price_per_share = 1780, minimum_investment = 1780 WHERE title ILIKE '%CFAC%';
UPDATE public.investment_offers SET price_per_share = 5300, minimum_investment = 5300 WHERE title ILIKE '%CIEC%';
UPDATE public.investment_offers SET price_per_share = 17270, minimum_investment = 17270 WHERE title ILIKE '%ECOC%' AND title NOT ILIKE '%ETIT%';
UPDATE public.investment_offers SET price_per_share = 46, minimum_investment = 3000 WHERE title ILIKE '%ETIT%';
UPDATE public.investment_offers SET price_per_share = 2055, minimum_investment = 2055 WHERE title ILIKE '%FTSC%';
UPDATE public.investment_offers SET price_per_share = 4350, minimum_investment = 4350 WHERE title ILIKE '%LNBB%';
UPDATE public.investment_offers SET price_per_share = 2270, minimum_investment = 2270 WHERE title ILIKE '%NEIC%';
UPDATE public.investment_offers SET price_per_share = 19990, minimum_investment = 19990 WHERE title ILIKE '%NSBC%';
UPDATE public.investment_offers SET price_per_share = 16450, minimum_investment = 16450 WHERE title ILIKE '%NTLC%';
UPDATE public.investment_offers SET price_per_share = 2800, minimum_investment = 2800 WHERE title ILIKE '%ONTBF%';
UPDATE public.investment_offers SET price_per_share = 16750, minimum_investment = 16750 WHERE title ILIKE '%ORAC%';
UPDATE public.investment_offers SET price_per_share = 2700, minimum_investment = 2700 WHERE title ILIKE '%ORGT%';
UPDATE public.investment_offers SET price_per_share = 8835, minimum_investment = 8835 WHERE title ILIKE '%PALC%';
UPDATE public.investment_offers SET price_per_share = 4520, minimum_investment = 4520 WHERE title ILIKE '%PRSC%';
UPDATE public.investment_offers SET price_per_share = 4555, minimum_investment = 4555 WHERE title ILIKE '%SAFC%';
UPDATE public.investment_offers SET price_per_share = 3625, minimum_investment = 3625 WHERE title ILIKE '%SCRC%';
UPDATE public.investment_offers SET price_per_share = 12045, minimum_investment = 12045 WHERE title ILIKE '%SDCC%';
UPDATE public.investment_offers SET price_per_share = 2435, minimum_investment = 2435 WHERE title ILIKE '%SDSC%';
UPDATE public.investment_offers SET price_per_share = 1505, minimum_investment = 1505 WHERE title ILIKE '%SEMC%';
UPDATE public.investment_offers SET price_per_share = 37000, minimum_investment = 37000 WHERE title ILIKE '%SGBC%';
UPDATE public.investment_offers SET price_per_share = 2200, minimum_investment = 2200 WHERE title ILIKE '%SHEC%';
UPDATE public.investment_offers SET price_per_share = 9000, minimum_investment = 9000 WHERE title ILIKE '%SIBC%';
UPDATE public.investment_offers SET price_per_share = 5200, minimum_investment = 5200 WHERE title ILIKE '%SICC%';
UPDATE public.investment_offers SET price_per_share = 2390, minimum_investment = 2390 WHERE title ILIKE '%SIVC%';
UPDATE public.investment_offers SET price_per_share = 40000, minimum_investment = 40000 WHERE title ILIKE '%SLBC%';
UPDATE public.investment_offers SET price_per_share = 17720, minimum_investment = 17720 WHERE title ILIKE '%SMBC%';
UPDATE public.investment_offers SET price_per_share = 29495, minimum_investment = 29495 WHERE title ILIKE '%SNTS%';
UPDATE public.investment_offers SET price_per_share = 8450, minimum_investment = 8450 WHERE title ILIKE '%SOGC%';
UPDATE public.investment_offers SET price_per_share = 7675, minimum_investment = 7675 WHERE title ILIKE '%SPHC%';
UPDATE public.investment_offers SET price_per_share = 3415, minimum_investment = 3415 WHERE title ILIKE '%STAC%';
UPDATE public.investment_offers SET price_per_share = 24015, minimum_investment = 24015 WHERE title ILIKE '%STBC%';
UPDATE public.investment_offers SET price_per_share = 2900, minimum_investment = 2900 WHERE title ILIKE '%TTLC%';
UPDATE public.investment_offers SET price_per_share = 4045, minimum_investment = 4045 WHERE title ILIKE '%TTLS%';
UPDATE public.investment_offers SET price_per_share = 51395, minimum_investment = 51395 WHERE title ILIKE '%UNLC%';
UPDATE public.investment_offers SET price_per_share = 1535, minimum_investment = 1535 WHERE title ILIKE '%UNXC%';

-- Ensuite, exécutez adjust_balances_after_price_update.sql pour créditer les soldes des investisseurs.
